dataset:
  name: "cwt_scalogram"
  type: "CWTScalogramDataset"
  splits:
    train:
      'B': [1,2,3,4,5,6,7,8]
    val:
      'B': [9,10]
    test:
      'B': [9,10]
  channels: ["A"]
  labels:
    "lv0": [0.6]
    "lv1": [0.5]
    "lv2": [0.4]
    "lv3": [0.3]
    "lv4": [0.2]
    "lv5": [0.1]
    "lv6": [0.05]
    