preprocess:
  filters: []
  norms:
    - name: SeriesZScoreNorm
      params:
        series_params:
          'B':
            mean: [0.5701, 1.9064, 0.2867]
            std: [4.8631, 7.0423, 8.2204]
          'C':
            mean: [0.1641, 1.7402, 0.5991]
            std: [4.8782, 7.7206, 9.0799]
          'D':
            mean: [0.5739, 1.8024, 0.7109]
            std: [5.7224, 6.8116, 8.6751]
          'E':
            mean: [0.5863, 1.9145, 0.4050]
            std: [5.2200, 6.2897, 8.1149]
          'F':
            mean: [0.1317, 1.2894, 0.4790]
            std: [4.9361, 5.8156, 8.1881]
  miscs:         
  - name: HanningWindow
    params: {}