preprocess:
  filters: 
  - name: HighPassFilter
    params:
      cutoff: 100000
      fs: 5.0e6
      order: 5
  norms:
    - name: SeriesZScoreNorm
      params:
        series_params:
          'B':
            mean: [0.3759, 1.8493, 0.3253]
            std: [4.6750, 6.3827, 7.3925]
          'C':
            mean: [0.8265, 2.0594, 0.1856]
            std: [4.6247, 7.1952, 8.4633]
          'D':
            mean: [0.3539, 2.0712, 0.8113]
            std: [4.8059, 7.2565, 8.9491]
          'E':
            mean: [0.1878, 1.1858, 0.4501]
            std: [4.9173, 6.6788, 9.3395]
          'F':
            mean: [0.5789, 2.0564, 0.4063]
            std: [4.8573, 6.1944, 8.3403]
  miscs:         
  - name: HanningWindow
    params: {}

