dataset:
  name: "cwt_scalogram"
  type: "CWTScalogramDataset"
  splits:
    train_val:
      type: chunk-based
      train: [0,1,2,3,4,5,6,7]
      val: [8,9]
    test: ['F']
  channels: ["A"]
  labels:
    "lv0": [0.05]
    "lv1": [0.1]
    "lv2": [0.2]
    "lv3": [0.3]
    "lv4": [0.4]
    "lv5": [0.5]
    "lv6": [0.6]