dataset:
  name: "cwt_scalogram"
  type: "CWTScalogramDataset"
  splits:
    train:
      'B': [1,2,3,4,5,6,7,8]
      'C': [1,2,3,4,5,6,7,8]
      'D': [1,2,3,4,5,6,7,8]
      'E': [1,2,3,4,5,6,7,8]
      'F': [1,2,3,4,5,6,7,8]
    val:
      'B': [9]
      'C': [9]
      'D': [9]
      'E': [9]
      'F': [9]
    test:
      'B': [10]
      'C': [10]
      'D': [10]
      'E': [10]
      'F': [10]
  channels: ["B"]
  labels:
    "lv0": [0.05]
    "lv1": [0.1]
    "lv2": [0.2]
    "lv3": [0.3]
    "lv4": [0.4]
    "lv5": [0.5]
    "lv6": [0.6]